### ISSUE TITLE
fetchAF2 doesn't properly load all structures

### ISSUE THREAD

**Issue by florisvdf** [APAJanssen/Alphafold2import#1]
I can load most structures without any issues, but sometimes I get:

```
PyMOL>fetchAF2 P04747
Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/internal.py", line 303, in file_read
    handle = urllib2.urlopen(req)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pmg_tk/startup/Alphafold2import/__init__.py", line 119, in _fetchAF2
    contents = _self.file_read(url)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pymol/internal.py", line 309, in file_read
    raise pymol.CmdException('failed to open file "%s"' % finfo)
pymol.CmdException:  Error: failed to open file "https://alphafold.ebi.ac.uk/files/AF-P04747-F1-model_v1.cif"
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pmg_tk/startup/Alphafold2import/__init__.py", line 258, in fetchAF2
    r = _multifetchAF2(*args)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pmg_tk/startup/Alphafold2import/__init__.py", line 187, in _multifetchAF2
    discrete, multiplex, zoom, type, path, file, quiet, _self)
  File "/Applications/PyMOL.app/Contents/lib/python3.7/site-packages/pmg_tk/startup/Alphafold2import/__init__.py", line 127, in _fetchAF2
    colorprinting.warning(" Warning: failed to fetch from %s" % (url,))
NameError: name 'colorprinting' is not defined
```

**Comment by APAJanssen** [comment]
Hi Floris,

Thank you for reaching out. This is actually EBIs 'fault', as they, to their absolute credit, sometimes update the posted models. This gets a new version number, part of the fetching URL (model_v1). When writing the module, all were v1, so this was hardcoded. I just uploaded a patched version that tries to find the newest version and downloads that. Tested on your P04747, and nicely fetches v2. Hope this helps!
Cheers,
Anthe

**Comment by florisvdf** [comment]
Thanks for getting back to me, I did not expect a response so soon! And also thanks for immediately patching this. However, it appears that the zip is no longer in the repo

**Comment by APAJanssen** [comment]
I happened to have some time, and ran into the same issue too from time to time.
The zip is indeed no longer there, as Github actually conveniently zips all files upon download. I've updated the Readme to reflect this, basically:
Download the files as .zip by clicking the green 'Code' button, and 'Download ZIP'.

**Comment by florisvdf** [comment]
I see, many thanks! I can now properly fetch the structure :)
